"""empty message

Revision ID: 1b43b6a4ef5a
Revises: b13eb713c716
Create Date: 2020-10-24 17:01:02.348720

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b43b6a4ef5a'
down_revision = 'b13eb713c716'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('talent_description', sa.String(length=120), nullable=True))
    op.drop_column('Venue', 'seeking_description')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('seeking_description', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.drop_column('Venue', 'talent_description')
    # ### end Alembic commands ###
